function gen_fig_5d(getcolumn1, getcolumn2, getcolumn3,getcolumn4,getc5,getc6,psi_est)
%CREATEFIGURE(PHI_OUT1, GETCOLUMN1, GETCOLUMN2, GETCOLUMN3)
%  PHI_OUT1:  vector of x data
%  GETCOLUMN1:  vector of y data psi
%  GETCOLUMN2:  stairs y psi_r
%  GETCOLUMN3:  vector of y data delta
% 4 bias estimate
% 5 psi_w
% 6 psi_w_est

%  Auto-generated by MATLAB on 10-Nov-2016 13:40:09

% Create figure
figure1 = figure;

% Create subplot
subplot1 = subplot(3,1,1,'Parent',figure1);
hold(subplot1,'on');

% Create plot
plot(getcolumn1,'Parent',subplot1,'DisplayName','$$\psi$$ measured');
plot(psi_est,'Parent',subplot1,'DisplayName','$$\hat{\psi}$$');

% Create stairs
plot(getcolumn2,'Parent',subplot1,'DisplayName','$$\psi_r$$','LineStyle',':');

% Create ylabel
ylabel({'Compass angle (\circ)'});

% Create legend
legend1 = legend(subplot1,'show');
set(legend1,'Interpreter','latex');
set(legend1,...
    'Position',[0.781596977016391 0.64437761007667 0.0949681072603464 0.108070178987508],...
    'EdgeColor',[1 1 1]);

% Create title
title({'Step response with current and wave disturbance'});

box(subplot1,'on');
% Create subplot
subplot2 = subplot(3,1,2,'Parent',figure1);
hold(subplot2,'on');

% Create plot
plot(getcolumn3,'Parent',subplot2,'DisplayName','$$\delta$$');
plot(getcolumn4,'Parent',subplot2,'DisplayName','$$\hat{b}$$');

legend2 = legend(subplot2,'show');
set(legend2,'Interpreter','latex');
set(legend2,...
    'EdgeColor',[1 1 1]);

% Create ylabel
ylabel({'Rudder angle and bias (\circ)'});

box(subplot2,'on');

% Create subplot
subplot3 = subplot(3,1,3,'Parent',figure1);
hold(subplot3,'on');

% Create plot
plot(getc5,'Parent',subplot3,'DisplayName','$$\psi_w$$');
plot(getc6,'Parent',subplot3,'DisplayName','$$\hat{\psi}_w$$');

legend2 = legend(subplot3,'show');
set(legend2,'Interpreter','latex')
set(legend2,...
    'EdgeColor',[1 1 1]);
% Create xlabel
xlabel({'Time (seconds)'});

% Create ylabel
ylabel({'Wave disturbance (\circ)'});

box(subplot3,'on');