function gen_fig_3(getcolumn1, getcolumn2, getcolumn3)
%CREATEFIGURE(PHI_OUT1, GETCOLUMN1, GETCOLUMN2, GETCOLUMN3)
%  PHI_OUT1:  vector of x data
%  GETCOLUMN1:  vector of y data
%  GETCOLUMN2:  stairs y
%  GETCOLUMN3:  vector of y data

%  Auto-generated by MATLAB on 10-Nov-2016 13:40:09

% Create figure
figure1 = figure;

% Create subplot
subplot1 = subplot(2,1,1,'Parent',figure1);
hold(subplot1,'on');

% Create plot
plot(getcolumn1,'Parent',subplot1,'DisplayName','\psi');

% Create stairs
plot(getcolumn2,'Parent',subplot1,'DisplayName','\psi_r','LineStyle',':');

% Create xlabel
xlabel(' ');

% Create ylabel
ylabel({'Compass angle (\circ)'});

% Create legend
legend1 = legend(subplot1,'show');
set(legend1,...
    'Position',[0.781596977016391 0.64437761007667 0.0949681072603464 0.108070178987508],...
    'EdgeColor',[1 1 1]);

% Create title
title({'Step response with no disturbance'});

box(subplot1,'on');
% Create subplot
subplot2 = subplot(2,1,2,'Parent',figure1);
hold(subplot2,'on');

% Create plot
plot(getcolumn3,'Parent',subplot2,'DisplayName','\delta');

% Create xlabel
xlabel({'Time (seconds)'});

% Create ylabel
ylabel({'Rudder angle (\circ)'});

% Create title
title({''});

box(subplot2,'on');
